<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCampaignsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
    */
    public function up()
    {
        Schema::create('campaigns', function (Blueprint $table) {
            $table->id();
            $table->string('reference');
            $table->integer('unit')->default(0)->comments('no of followers for campaign');
            $table->float('amount')->default(0.00)->comments('Campaign selling price');
            $table->boolean('live')->default(false);
            $table->boolean('status')->default(true)->comments('this is markes campaign open or closed once the the unit value is equals completed target.');
            $table->boolean('completed')->default(false)->comments('Admin will set to true on settlement');
            $table->string('facebook_post_link')->nullable();
            $table->string('facebook_reference')->nullable()->comments('this will be generated by frontend app for unique identifier');
            $table->string('instagram_post_link')->nullable();
            $table->string('instagram_reference')->nullable();
            $table->string('youtube_post_link')->nullable();
            $table->string('youtube_reference')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('campaigns');
    }
}
